name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels:
  - "bug"
  - "unconfirmed"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      options:
        - 1.20.2
        - 1.20.4
        - 1.20.5
        - 1.20.6
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      options:
        - NeoForge
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: WuidebookAPI Version
    validations:
      required: true
  - type: input
    id: loader-version
    attributes:
      label: ModLoader Version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened ?
      description: Please describe what happened or what you expected instead
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduce Steps
      description: Please describe how to reproduce your issue
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. If your game crashes, this must be a crash-report
      render: shell
