modLoader="javafml"
loaderVersion="${neo_loader}"
license="${mod_license}"
issueTrackerURL="https://github.com/wonejomb/GuidebookAPI/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
    [[dependencies.${mod_id}]]
        modId="neoforge"
        type="required"
        versionRange="${neo_range}"
        ordering="NONE"
        side="BOTH"

[[mixins]]
config="wuidebook.mixins.json"