name: Build PRs

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
  push:
    branches: 
      - 'feature/**'

jobs:
  build:
    runs-on: ubutun-latest
    steps:
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                cache-read-only: false

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 1000
                fetch-tags: true
