name: Build and test PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Notify Pending Build
        uses: wonejomb/webhook-actions@2.0.10
        with:
          webhook_url: ${{ secrets.webhook_url }}
          webhook_name: 'GuidebookAPI/Github'
          status: 'started'
          webhook_avatar: ${{ secrets.webhook_avatar }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Setup Gradle Permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        run: ./gradlew

#      - name: Build Gradle
#        run: ./gradlew build

#      - name: Run gradle test
#        run: ./gradlew test

      - name: Store Reports
        if: failure ()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results

      - name: Notify Success Build
        if: success()
        uses: wonejomb/webhook-actions@2.0.10
        with:
          webhook_url: ${{ secrets.webhook_url }}
          webhook_name: 'GuidebookAPI/Github'
          status: 'success'
          webhook_avatar: ${{ secrets.webhook_avatar }}

      - name: Notify Failure Build
        if: failure ()
        uses: wonejomb/webhook-actions@2.0.10
        with:
          webhook_url: ${{ secrets.webhook_url }}
          webhook_name: 'GuidebookAPI/Github'
          status: 'failure'
          webhook_avatar: ${{ secrets.webhook_avatar }}