name: Build PRs

on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch_depth: 1000
          fetch_tags: true

      - name: Create branch for commit
        run:
          git switch -C pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false